# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  PHP: false
  Python: true
exclude_paths:
- "analytics/*"
- "cleanDataset/*"
- "originalDataset/*"
